version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-payments}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:25432"

  php-fpm:
    container_name: php-fpm
    build:
      context: ./dockerfiles/php-fpm
    networks:
      - my-network
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      XDEBUG_CONFIG: 'idekey=PHPSTORM remote_host=host.docker.internal remote_port=9000 remote_autostart=1 remote_enable=1 remote_mode=req remote_connect_back=0'
      PHP_IDE_CONFIG: 'serverName=DockerPayments'
    volumes:
      - ./:/var/www
    expose:
      - 9000

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-network
    environment:
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
    ports:
      - "5672:25672"

  nginx:
    container_name: nginx
    build:
      context: ./dockerfiles/nginx
    networks:
      - my-network
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockerfiles/nginx/sites/:/etc/nginx/sites-available
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d
      - ./dockerfiles/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

volumes:
  mercure_data:
  mercure_config:
  db-data:

networks:
  my-network:
    driver: bridge
